// GENERATED by scripts/resolve-angelone-tokens.mjs — do not edit by hand.
import type { AngelInstrument } from "./instruments.js";

export const angelInstruments: Record<string, AngelInstrument> = {
  "RELIANCE": {
    "token": "2885",
    "exchangeType": 1,
    "exchange": "NSE"
  },
  "TCS": {
    "token": "11536",
    "exchangeType": 1,
    "exchange": "NSE"
  },
  "HDFCBANK": {
    "token": "1333",
    "exchangeType": 1,
    "exchange": "NSE"
  },
  "INFY": {
    "token": "1594",
    "exchangeType": 1,
    "exchange": "NSE"
  },
  "ICICIBANK": {
    "token": "4963",
    "exchangeType": 1,
    "exchange": "NSE"
  },
  "HINDUNILVR": {
    "token": "1394",
    "exchangeType": 1,
    "exchange": "NSE"
  },
  "SBIN": {
    "token": "3045",
    "exchangeType": 1,
    "exchange": "NSE"
  },
  "NIFTY50": {
    "token": "99926000",
    "exchangeType": 1,
    "exchange": "NSE"
  },
  "SENSEX": {
    "token": "99919000",
    "exchangeType": 3,
    "exchange": "BSE"
  }
};
